# .streamlit/secrets.toml

[files]
orders_path = "C:/Users/alsuu3/OneDrive - IKEA/Documents/Python Projects/AD HOC/Click and Collect Treshold/Input Data/CnC_Orders.json"
calendar_path = "C:/Users/alsuu3/OneDrive - IKEA/Documents/Python Projects/AD HOC/Click and Collect Treshold/Input Data/IKEA_calendar.json"

[auth]
username = "mycolleague"
password = "secretpassword123"
